### ISSUE TITLE
Add no-op

### ISSUE THREAD

**Issue by alorma** [Sloy/preferator#2]
Thanks for this work!

Adding a `no-op` version will allow to not set a debug check in the code.

Ex: in the app build version, if `no-op` is available, it doesn't need to make the if inside the click listener

**Comment by CristianGM** [comment]
Click listener? Would you have a button without click action?

I think you'll need the if anyway to hide the button ( or whatever you use to access ).

IMHO no-op is for libs that do something at all the system wide, like metrics, crash logs, memory trackers...all of them do things without user interaction.

**Comment by Sloy** [comment]
Thanks for the suggestion @alorma.
I agree with @CristianGM, I don't really see much use for a no-op since you will probably want to hide the button or trigger anyways.

Maybe just to avoid including the code in the apk just in case?

**Comment by jp1017** [comment]
> Maybe just to avoid including the code in the apk just in case

Yes. haha, :smile:

**Comment by Sloy** [comment]
Added on #5. I'm closing the issue.
Will be released with the next version.
